version: '3'
services:
  app:
    tty: true
    image: node:8
    working_dir: /app
    ports:
      - "${SANDBOX_PORT-5623}:${SANDBOX_PORT-5623}"
    environment:
        PORT: ${SANDBOX_PORT-5623}
    volumes:
      - .:/app:cached
      - node_modules:/app/node_modules
    restart: on-failure
    entrypoint: "/app/start.sh"
volumes:
  node_modules: {}
